#!/bin/bash

echo "Enter first number:"
read num1

echo "Enter second number:"
read num2


if [ "$num1" -eq "$num2" ]; then
    echo "Both numbers are equal."
else
    echo "Numbers are not equal."
fi
